name: C++ Pull Request CI

on:
  pull_request:
    branches:
      - server-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install C++ environment
      run: |
        sudo apt update
        sudo apt install -y build-essential
        sudo apt install -y cmake # Install cmake if you don't already have it

    - name: Build Project
      run: |
        cmake -B build -S .
        cmake --build build
