name: C++ Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install C++ environment
      run: |
        sudo apt update
        sudo apt install -y build-essential
        sudo apt install -y libgtest-dev
        sudo apt install -y cmake # Install cmake if you don't already have it
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        
    - name: Build Project
      run: |
       cmake -B build -S .
    - name : Second Build
      run: |
        cmake --build build
    - name: Run Tests
      run: |
        ctest --test-dir build --output-on-failure --verbose